### ISSUE TITLE
Percentage values differ between Xiaomi App and Homekit

### ISSUE THREAD

**Issue by harryslapalot** [russtone/homebridge-mi-humidifier#57]
I use the plugin with deerma.humidifier.mjjsq

Unfortunately the humidity percentage values are not the same in the Xiaomi App and Homekit. The actual humidity is correct in Homekit, but the target humidity always differs by a few percent (e.g. 54% in App corresponds to 48% in Homekit).
Also it shouldn't be possible to set a value greater than 70% or lower than 40% (which are the max and min levels in the app)

**Comment by bubffm** [comment]
Same peoblem. My humidity target in Homekit always says 44% - whatever the a tually set target says.

**Comment by russtone** [comment]
This issue should be fixed in the latest version. But it won't work until you clear a cache.
To reset the cache you need to:
1. Add `"disabled": true` flag to the device config
2. Restart homebridge and wait for the device to disappear
3. Remove `"disabled"` flag from the device config or set it to `false`
4. Restart homebridge again
